import { z } from "zod";

/**
 * The code for a course subject
 */
export type SubjectCode = keyof typeof Subject;

/**
 * An enumeration of subject codes and subject
 */
export enum Subject {
  ACCT = "Accounting",
  ADCN = "Addiction Counseling",
  AIRS = "Air Force ROTC",
  AMOA = "Administrative Medical Office",
  APOL = "Apologetics",
  ARAB = "Arabic",
  ARTS = "Art",
  ASCS = "Academic Success Center Studie",
  ASLI = "American Sign Language",
  ATTR = "Athletic Training", // 10
  AVIA = "Aviation",
  AVMT = "Aviation Maintenance",
  AVMX = "Aviation Maintenance Mgmt",
  BCHM = "Biochemistry",
  BIBL = "Bible",
  BIOL = "Biology",
  BIOM = "Biomedical Sciences",
  BMAL = "Business Management & Leadersh",
  BMIS = "Business Management Info Sys",
  BUSI = "Business", // 20
  CARP = "Carpentry",
  CCOU = "Christian Counseling",
  CEFS = "Counseling - CEFS",
  CFRE = "Conversational French",
  CGRM = "Conversational German",
  CHEM = "Chemistry",
  CHHI = "Church History",
  CHIN = "Chinese",
  CHMN = "Church Ministries",
  CHPL = "Chaplaincy", // 30
  CINE = "Cinematic Arts",
  CJUS = "Criminal Justice",
  CLCM = "Christian Lead & Ch Ministries",
  CLED = "Christian Leadership",
  CLST = "College Learning Strategies",
  CMUS = "Commercial Music",
  COMS = "Communication Studies",
  COSC = "Counseling: School Counseling",
  COUC = "Counseling - COUC",
  CPED = "Clinical Pastoral Education", // 40
  CRFT = "Core Craft Skills",
  CRIS = "Crisis Counseling",
  CRST = "Creation Studies",
  CSCI = "Computer Science - CSCI",
  CSCN = "Computer Science - CSCN",
  CSIS = "Computer Science Info Systems",
  CSPA = "Conversational Spanish",
  CSTU = "Cultural Studies", // 25% (48)
  DBFA = "Dobson Family Studies",
  DBMF = "Dobson Marriage & Family", // 50
  DBPC = "Dobson Psyc Perspectives",
  DIGI = "Digital Arts",
  DISS = "Dissertation",
  DMCA = "Digital Media & Communication",
  DMIN = "Doctor of Ministry",
  DSMN = "Discipleship Ministries",
  ECON = "Economics",
  EDAS = "Education Admin & Supervision",
  EDCO = "Community Care and Counseling",
  EDDR = "Education Doctoral Research", // 60
  EDEC = "Education Early Childhood",
  EDGL = "Education Gifted Learner",
  EDGT = "Education Gate",
  EDMS = "Education Math Specialist",
  EDRS = "Education Reading Specialist",
  EDSC = "Education Science",
  EDSP = "Special Education",
  EDST = "Education Student Training",
  EDUC = "Education",
  ELTC = "Electrical", // 70
  EMGT = "Event Management",
  ENGC = "Engineering: Computer Eng",
  ENGE = "Engineering: Electrical Eng",
  ENGI = "Engineering: Industrial Eng",
  ENGL = "English",
  ENGM = "Engineering: Mechanical Eng",
  ENGR = "Engineering: General",
  ENGV = "Engineering: Civil Eng",
  ENVR = "Environmental Science",
  ESLP = "Eagle Scholar Leadership Progr", // 80
  ETHC = "Ethics",
  ETHM = "Ethnomusicology",
  EVAN = "Evangelism",
  EVCP = "Evangelism and Church Planting",
  EXSC = "Exercise Science",
  FACS = "Family and Consumer Sciences",
  FIRE = "Fire Administration",
  FNLT = "Financial Literacy",
  FREN = "French",
  GBST = "General Bible Studies", // 90
  GEOG = "Geography",
  GLST = "Global Studies",
  GOVT = "Government",
  GREK = "Greek",
  GRMN = "German",
  GRST = "Graduate Studies", // 50% (96)
  GUNS = "Shooting Safety and Skills",
  HBRW = "Hebrew",
  HIEU = "History: European History",
  HIST = "History", // 100
  HIUS = "History: United States History",
  HIWD = "History - Wold History",
  HLSC = "Homeland Security",
  HLTH = "Health",
  HMGT = "Hospitality Management",
  HOMI = "Homiletics",
  HONR = "Honors",
  HSCI = "Health Sciences",
  HSCO = "Human Services Counseling",
  HSER = "Human Services", // 110
  HSMF = "Marriage and Family",
  HUMR = "Human Rights",
  HVAC = "Heating, Ventilation, Air Cond",
  INDS = "Interdisciplinary Studies",
  INFO = "Informatics",
  INFT = "Information Technology",
  INQR = "Inquiry",
  INTL = "International Relations",
  JOUR = "Journalism",
  JURI = "Juris Master Law", // 120
  LANG = "Foreign Language",
  LAW = "Law",
  LEAD = "Leadership",
  LIFC = "Life Coaching",
  LING = "Linguistics",
  LPCY = "Law and Policy",
  MATH = "Mathematics",
  MENT = "Mentoring",
  MGMT = "Management",
  MILT = "Military", // 130
  MISC = "Military Science",
  MLAN = "Modern Languages",
  MRKT = "Marketing",
  MSCI = "Medical Science",
  MSPS = "Psychology - MSPS",
  MUSC = "Music",
  NASC = "Natural Science",
  NBST = "New Testament Bible Studies",
  NGRK = "New Testament Greek",
  NSEC = "National Security", // 140
  NURS = "Nursing",
  NUTR = "Nutrition",
  OBST = "Old Testament Bible Studies",
  OTCL = "Old Testament Cognate Lang", // 75% (144)
  PACO = "Pastoral Counseling",
  PADM = "Public Administration",
  PHED = "Physical Education",
  PHGT = "Public Health Gate",
  PHIL = "Philosophy",
  PHSC = "Physical Science", // 150
  PHYS = "Physics",
  PLCY = "Public Policy",
  PLED = "Pastoral Leadership",
  PLMB = "Plumbing",
  PLST = "Paralegal Studies - LUO",
  PPOG = "Public Policy: Government",
  PPOL = "Public Policy: Law",
  PRTH = "Practical Theology",
  PSCI = "Political Science",
  PSYC = "Psychology - PSYC", // 160
  PSYD = "Clinical Psychology",
  RASP = "Research Admin and Sponsored Pro",
  RESP = "Respiratory Therapy",
  RLGN = "Religion",
  RLST = "Religious Studies",
  RSCH = "Research",
  RTCH = "Research Methods & Teaching",
  RUSS = "Russian",
  SCOM = "Speech Communication",
  SETM = "Sport, Event & Tourism Mgmt", // 170
  SFME = "Supervised Field Ministry Exp",
  SMGT = "Sport Management",
  SOCI = "Sociology",
  SOWK = "Social Work",
  SPAN = "Spanish",
  STCO = "Strategic Communication",
  SUBS = "Substance Abuse",
  TESL = "Teaching English as Sec Lang",
  THEA = "Theatre",
  THEO = "Theology", // 180
  THES = "Thesis",
  TOUR = "Tourism",
  TRMA = "Traumatology",
  UNIV = "University Core Competencies",
  WELD = "Welding",
  WLED = "Women's Leadership",
  WMUS = "Worship Music",
  WRIT = "Writing",
  WRSP = "Worship Studies",
  YOUT = "Youth", // 190
}

/**
 * A constant array of subject codes
 */
export const subjectCodes = [
  "ACCT",
  "ADCN",
  "AIRS",
  "AMOA",
  "APOL",
  "ARAB",
  "ARTS",
  "ASCS",
  "ASLI",
  "ATTR", // 10
  "AVIA",
  "AVMT",
  "AVMX",
  "BCHM",
  "BIBL",
  "BIOL",
  "BIOM",
  "BMAL",
  "BMIS",
  "BUSI", // 20
  "CARP",
  "CCOU",
  "CEFS",
  "CFRE",
  "CGRM",
  "CHEM",
  "CHHI",
  "CHIN",
  "CHMN",
  "CHPL", // 30
  "CINE",
  "CJUS",
  "CLCM",
  "CLED",
  "CLST",
  "CMUS",
  "COMS",
  "COSC",
  "COUC",
  "CPED", // 40
  "CRFT",
  "CRIS",
  "CRST",
  "CSCI",
  "CSCN",
  "CSIS",
  "CSPA",
  "CSTU", // 25% (48)
  "DBFA",
  "DBMF", // 50
  "DBPC",
  "DIGI",
  "DISS",
  "DMCA",
  "DMIN",
  "DSMN",
  "ECON",
  "EDAS",
  "EDCO",
  "EDDR", // 60
  "EDEC",
  "EDGL",
  "EDGT",
  "EDMS",
  "EDRS",
  "EDSC",
  "EDSP",
  "EDST",
  "EDUC",
  "ELTC", // 70
  "EMGT",
  "ENGC",
  "ENGE",
  "ENGI",
  "ENGL",
  "ENGM",
  "ENGR",
  "ENGV",
  "ENVR",
  "ESLP", // 80
  "ETHC",
  "ETHM",
  "EVAN",
  "EVCP",
  "EXSC",
  "FACS",
  "FIRE",
  "FNLT",
  "FREN",
  "GBST", // 90
  "GEOG",
  "GLST",
  "GOVT",
  "GREK",
  "GRMN",
  "GRST", // 50% (96)
  "GUNS",
  "HBRW",
  "HIEU",
  "HIST", // 100
  "HIUS",
  "HIWD",
  "HLSC",
  "HLTH",
  "HMGT",
  "HOMI",
  "HONR",
  "HSCI",
  "HSCO",
  "HSER", // 110
  "HSMF",
  "HUMR",
  "HVAC",
  "INDS",
  "INFO",
  "INFT",
  "INQR",
  "INTL",
  "JOUR",
  "JURI", // 120
  "LANG",
  "LAW",
  "LEAD",
  "LIFC",
  "LING",
  "LPCY",
  "MATH",
  "MENT",
  "MGMT",
  "MILT", // 130
  "MISC",
  "MLAN",
  "MRKT",
  "MSCI",
  "MSPS",
  "MUSC",
  "NASC",
  "NBST",
  "NGRK",
  "NSEC", // 140
  "NURS",
  "NUTR",
  "OBST",
  "OTCL", // 75% (144)
  "PACO",
  "PADM",
  "PHED",
  "PHGT",
  "PHIL",
  "PHSC", // 150
  "PHYS",
  "PLCY",
  "PLED",
  "PLMB",
  "PLST",
  "PPOG",
  "PPOL",
  "PRTH",
  "PSCI",
  "PSYC", // 160
  "PSYD",
  "RASP",
  "RESP",
  "RLGN",
  "RLST",
  "RSCH",
  "RTCH",
  "RUSS",
  "SCOM",
  "SETM", // 170
  "SFME",
  "SMGT",
  "SOCI",
  "SOWK",
  "SPAN",
  "STCO",
  "SUBS",
  "TESL",
  "THEA",
  "THEO", // 180
  "THES",
  "TOUR",
  "TRMA",
  "UNIV",
  "WELD",
  "WLED",
  "WMUS",
  "WRIT",
  "WRSP",
  "YOUT", // 190
] as const;

/**
 * A pre-fabricated Zod validator for subject codes
 */
export const subjectCodesVal = z.enum(subjectCodes);
